<center>
<table style="border:none">
    <tr style="border:none">
    <th style="border:none">
        <a  href='https://colab.research.google.com/github/AmirMardan/ml_course/blob/main/2_numpy/0_intro_to_numpy.ipynb'><img src='https://colab.research.google.com/assets/colab-badge.svg'></a>
    </th>
    <th style="border:none">
        <a  href='https://github1s.com/AmirMardan/ml_course/blob/main/2_numpy/0_intro_to_numpy.ipynb'><img src='../imgs/open_vscode.svg' height=20px width=115px></a>
    </th>
    </tr>
</table>
</center>


This notebook is created by <a href='https://amirmardan.github.io'> Amir Mardan</a>. For any feedback or suggestion, please contact me via my <a href="mailto:mardan.amir.h@gmail.com">email</a>, (mardan.amir.h@gmail.com).



<center>
<img src='img/numpy.png' width='300px'>
</center>

<a name='top'></a>
# Introdunction to NumPy

This notebook will cover the following topics:

- [Introduction](#introduction)
- [NumPy vs list](#numpy_list) 
- [1. Creating a NumPy array](#creating) 
    - [Creating arrays from lists](#creating_with_list) 
    - [Special arrays](#special_array) 
- [2 Attributes of arrays](#attributes_array) 
- [3. Data Selection](#data_election) 
    - [Array indexing](#indexing) 
    - [Array slicing](#slicing) 
    - [Array view vs copy](#view_copy) 
    - [Conditional selection](#conditional) 
- [4. Array manipulation](#manipulation) 
    - [Shape of an array](#shape) 
    - [Joining arrays](#joining) 
    - [Splitting of arrays](#splitting) 
- [5. Computation on NumPy arrays ](#computation) 
- [6. Aggregations](#aggregations) 
    - [Summation](#summation) 
    - [Minimum and maximum](#min_max) 
    - [Variance and standard deviation](#var_std) 
    - [Mean and median](#mean_median) 
    - [Find index](#find_index) 

<a name='introduction'></a>
## Introduction 


NumPy is a library for working large, multi-dimensional arrays and matrices.
Created by **Travis Oliphant**, first time released in 1995 as *Numeric* and changed to *NumPy* in 2006.

<center><img src='./img/travis.jpeg' alter='tavis' width=300px></center>

The array object in NumPy is called `ndarray`

<a name='numpy_list'></a>
## NumPy vs list 


**Advantages of using NumPy arrays over Python lists**

- Numpy takes less memory
- Numpy is faster
- Numpy has better functionality

Let's try if these statements are true. But first, we need to tell Python, that we want to use Numpy. To do so, we import this package. Generally, a Python package can be imported at the beginning of a script as

```Python
 import module
```
To make us comfortable, Python lets us pick a nickname for a module we import using the keyword `as`,

```Python
 import module as nickname
```

In [2]:
# Import numpy 

import numpy as np

n = 1000

# Make an array of zeros
numpy_version = np.zeros(n)

list_version = list(numpy_version)

print(type(list_version), type(numpy_version))

<class 'list'> <class 'numpy.ndarray'>


<div class="alert alert-block alert-danger">
<b>Danger:</b> Please note that the addition of two lists causes concatenation!
</div>

In [3]:
def numpy_based():
    return  numpy_version + 5
    
    
def list_based():
    return [list_version[i] + 5 for i in range(len(list_version))]

In [4]:
%timeit list_based()
%timeit numpy_based()


225 µs ± 2.32 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
2.01 µs ± 41.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In lot's of material, we see the above example is used to show NumPy is fater but the truth is the function `list_based` is not implemented well. Let's write it with `map()` as we learned in introduction to Python.

In [5]:
def list_based():
    add = lambda a: a + 5
    return map(add, list_version)


%timeit list_based()
%timeit numpy_based()
print('Voila, list is faster now.')


205 ns ± 3.08 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
2.02 µs ± 19 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
Voila, list is faster now.


In [6]:
# Let's check the size and values 

a = numpy_based()
b = list_based()

c = list(b)
print("They're equal!\nNumPy: ", a.shape, "\nlist: ", np.shape(c)) if [np.all(c == a)] else print('Wrong!') 


They're equal!
NumPy:  (1000,) 
list:  (1000,)


But for sure, NumPy gives us more functionality and NumPy's methods are faster using NumPy arrays.

In [7]:
def numpy_based():
    return np.mean(numpy_version)


def list_based():
    return np.mean(list_version)


In [8]:
%timeit list_based()
%timeit numpy_based()

59 µs ± 2.13 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
10.1 µs ± 2.31 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


<a name='creating'></a>
## 1 . Creating a NumPy array 


`numpy.array` can be used to create a tensor

<center><img src='img/Tensor_01.webp' alt='tensor' width=400px></center>

In [9]:
# Create 0-D array

a = np.array(2)

print("a = ", a, "; shape: ", a.ndim)

a =  2 ; shape:  0


<a name='creating_with_list'></a>
### 1.1 Creating arrays from lists


We can use `np.array()` to create an array from Python lists

```Python
np.array(list_name)
```

In [10]:
# Create 1-D 'float' array

np.array([1.0, 4.3, 8., 9])

array([1. , 4.3, 8. , 9. ])

We can use the parameter `dtype` to specify the type of data,

```Python
np.array(list_name, dtype=desired_type)
```

In [11]:
# Create 1-D 'int' array

np.array([1.0, 4., 8., 9], dtype=np.int32)

array([1, 4, 8, 9], dtype=int32)

In [12]:
# Create 2-D array

np.array([[1.0, 4., 8., 9],
          [2, 4, 1, 3]], dtype=np.float32)

array([[1., 4., 8., 9.],
       [2., 4., 1., 3.]], dtype=float32)

<a name='special_array'></a>
### 1.2 Special arrays


It's better to use special methods in NumPy for larger arrays. These special arrays are:

- All zero array
- All one array
- Identity matrix
- Empty array
- Full array
- Random array
- Arrays based on a given range

These arrays are usually created with the following syntax:

```Python
np.array(shape=shape_in_tuple, dtype=type_of_data)
```


In [13]:
# Creating an array of zeros

np.zeros(shape=(5, 2), dtype=np.float32)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [14]:
# Creating an array of zeros using zeros_like

np.zeros_like(np.ones(shape=(5, 2), dtype=np.float32))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

To make it easier, we can let NumPy decide the type of data for the rest of this notebook.

In [15]:
# Creating an array of ones

np.ones(shape=(5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# Creating an identity matrix
# Note: np.eye doesn't get the sahpe as argument!

np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [17]:
# Creating an empty array

np.empty(shape=(5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
# Creating an empty array using empty_like

np.empty_like(np.zeros((5, 2)))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
# Creating an array of random numbers (normally distributed)

np.random.normal(loc=0, scale=1, size=(5,2))

array([[ 0.11722769,  0.76295362],
       [-2.17500568,  0.81683978],
       [ 1.50041677, -0.32196711],
       [-1.63829221,  0.57127079],
       [ 2.63541006,  0.4626389 ]])

In [20]:
# Creating an array of random numbers (uniformly distributed)

np.random.random((5, 2))

array([[0.03419494, 0.77326372],
       [0.78682513, 0.40468411],
       [0.79862319, 0.01839944],
       [0.83450445, 0.39707709],
       [0.23809996, 0.68961533]])

<hr>
<div>
<span style="color:#151D3B; font-weight:bold">Question: 🤔</span><p>
Generate an array with shape of [10, 10] and values between 5 and 7
</div>
<hr>

In [21]:
# Answer



In [22]:
# Creating an array of random numbers

np.random.rand(5, 2)

array([[0.4097082 , 0.80731176],
       [0.2891896 , 0.00881332],
       [0.26646891, 0.99539955],
       [0.87865244, 0.17352633],
       [0.68704688, 0.49754203]])

In [23]:
# Creating an array of random integer numbers

np.random.randint(low=1, high=5, size=(5, 2))

array([[1, 4],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 2]])

In [24]:
# Creating an array in a range

np.arange(start=1, stop=4, step=0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9])

In [25]:
# Creating an array in a range

np.linspace(start=1, stop=4, num=10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [26]:
# Creating an array in a range

np.logspace(start=1, stop=4, num=10)

array([   10.        ,    21.5443469 ,    46.41588834,   100.        ,
         215.443469  ,   464.15888336,  1000.        ,  2154.43469003,
        4641.58883361, 10000.        ])

<a name='attributes_array'></a>
## 2. Attributes of arrays 


We use attributes to determine some properties of the array such as shape, size, etc.

In [27]:
x = np.random.randint(14, size=(4, 3))

print(x)

[[ 8  3 13]
 [ 3  9  9]
 [ 8  3  3]
 [ 8  0  4]]


In [28]:
print("Dimension: ", x.ndim) 
print("Shape: ", x.shape) 
print("Size: ", x.size) 
print("Type: ", x.dtype)
print("Element size: ", x.itemsize, 'bytes')  # Size of each element
print("Array size: ", x.nbytes, 'bytes')  # Size of the array

Dimension:  2
Shape:  (4, 3)
Size:  12
Type:  int64
Element size:  8 bytes
Array size:  96 bytes


<a name='data_election'></a>
## 3. Data Selection
 

***Indexing*** is used to select an individual element of an array

***Slicing*** is used to select a part of an array

<a name='indexing'></a>
### 3.1 Array indexing

Please note that Python counts from `0`.

In [29]:
x_1d = np.random.random((6, 1))
x_1d

array([[0.92217528],
       [0.79863999],
       [0.94418079],
       [0.82755604],
       [0.63045452],
       [0.88990979]])

In [30]:
# Access to the first element

x_1d[0]

array([0.92217528])

In [31]:
# Access to the last element

x_1d[-1]

array([0.88990979])

In [32]:
x_2d = np.random.random((4, 5))
x_2d

array([[0.33885542, 0.1597375 , 0.07806182, 0.23368214, 0.06593179],
       [0.66934263, 0.81221089, 0.64326019, 0.01511344, 0.14241199],
       [0.43655335, 0.53837157, 0.82013621, 0.06432384, 0.72217852],
       [0.61336211, 0.41301832, 0.0147283 , 0.45730859, 0.03794812]])

In [33]:
x_2d[0, 0]

0.3388554239006373

In [34]:
x_2d[0][0]

0.3388554239006373

<hr>
<div>
<span style="color:#151D3B; font-weight:bold">Question: 🤔</span><p>
What would be the result of <code>x_2d[0, 0]</code>?
</div>
<hr>

In [35]:
# Answer

<a name='slicing'></a>
### 3.2 Array slicing

For a 1-D slicing we use the following syntax

```Python
sliced = original[begining:end:step]
```

If `step` is not given, it will be considered as `1`.


In [36]:
x_1d

array([[0.92217528],
       [0.79863999],
       [0.94418079],
       [0.82755604],
       [0.63045452],
       [0.88990979]])

In [37]:
# Specify the start and end of the desired section by number

x_1d[1:4]

array([[0.79863999],
       [0.94418079],
       [0.82755604]])

<div class="alert alert-block alert-info">
<b>Tip:</b> Please consider that element 1 is included but that's not the case for element 4.</div>

In [38]:
"""
Specify the start or the end of the desired section that corresponds to
the start or the end of the array
"""

x_1d[1:]

array([[0.79863999],
       [0.94418079],
       [0.82755604],
       [0.63045452],
       [0.88990979]])

In [39]:
# Indexing with step greater than 1

x_1d[1::2]

array([[0.79863999],
       [0.82755604],
       [0.88990979]])

In [40]:
# We can reverse the array by indexing

x_1d[-1:0:-1]

array([[0.88990979],
       [0.63045452],
       [0.82755604],
       [0.94418079],
       [0.79863999]])

In [41]:
# Slicing in 2-D

x_2d[1:, 3:5]

array([[0.01511344, 0.14241199],
       [0.06432384, 0.72217852],
       [0.45730859, 0.03794812]])

<a name='view_copy'></a>
### 3.3 Array view vs copy

An extremely important thing to know is array slices return *views* of data rather than *copy*.
This is another difference between NumPy arrays and Python lists. 

In [42]:
print(x_1d)

x_1d_sliced = x_1d[0]

x_1d_sliced *= 2

print("======== \n", x_1d)


[[0.92217528]
 [0.79863999]
 [0.94418079]
 [0.82755604]
 [0.63045452]
 [0.88990979]]
 [[1.84435057]
 [0.79863999]
 [0.94418079]
 [0.82755604]
 [0.63045452]
 [0.88990979]]


To prevent any problems, you should use the method `copy()`

In [43]:
print(x_1d)

x_1d_sliced = x_1d[0].copy()

x_1d_sliced *= 2

print("======== \n", x_1d)

[[1.84435057]
 [0.79863999]
 [0.94418079]
 [0.82755604]
 [0.63045452]
 [0.88990979]]
 [[1.84435057]
 [0.79863999]
 [0.94418079]
 [0.82755604]
 [0.63045452]
 [0.88990979]]


<a name='conditional'></a>
### 3.4 Conditional selection

We can use a condition to select a part of an array.

In [44]:
x_1d

array([[1.84435057],
       [0.79863999],
       [0.94418079],
       [0.82755604],
       [0.63045452],
       [0.88990979]])

In [45]:
# Let's create a condition

cond = x_1d > 0.7
cond

array([[ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True]])

In [46]:
# Select the data based on the condition

x_1d[cond]

array([1.84435057, 0.79863999, 0.94418079, 0.82755604, 0.88990979])

In [47]:
# Let's create a 2-D array

x_2d_int = np.random.randint(12, size=(5, 6))

x_2d_int

array([[ 9,  8,  3,  2,  1,  6],
       [11,  9,  1, 11,  9, 10],
       [ 8,  6,  1,  0,  8, 10],
       [ 0,  7,  5,  2, 10,  4],
       [ 4,  9,  1, 10,  0,  8]])

In [48]:
# Let's pull out the even numbers

x_2d_int[x_2d_int % 2 == 0]

array([ 8,  2,  6, 10,  8,  6,  0,  8, 10,  0,  2, 10,  4,  4, 10,  0,  8])

<hr>
<div>
<span style="color:#151D3B; font-weight:bold">Question: 🤔</span><p>
Using conditional indexing, pull out numbers in <code>x_2d_int</code> that are divisible by both 2 and 7.
</div>
<hr>

In [49]:
# Answer



<a name='manipulation'></a>
## 4. Array manipulation


Data manipulation is an important step in any study.

<a name='shape'></a>
### 4.1 Shape of an array


In [50]:
# Let's create some arrays

arr_1d = np.arange(10)
arr_2d = 5 * np.random.random((4, 5))


In [51]:
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr_2d

array([[3.12494865e+00, 2.52019245e+00, 1.66512359e+00, 4.41634994e+00,
        2.92805654e+00],
       [3.50692316e-01, 1.00497838e+00, 3.06787794e+00, 7.90607320e-01,
        3.09527984e+00],
       [2.42114524e+00, 2.04947916e+00, 3.24382176e-03, 2.82234526e+00,
        3.79200212e+00],
       [3.46652576e+00, 1.33838524e-01, 6.33470826e-01, 4.25387286e+00,
        4.02985249e+00]])

In [53]:
# Shape of an array can be obtained in 2 ways

print(arr_1d.shape, np.shape(arr_1d))

(10,) (10,)


In [54]:
arr_2d.shape

(4, 5)

We can easily reshape a NumPy array


```Python

array.reshape(rows, columns)

np.reshape(array, newshape=(rows, columns))

```

In [55]:
arr_2d.reshape(5, 4)

array([[3.12494865e+00, 2.52019245e+00, 1.66512359e+00, 4.41634994e+00],
       [2.92805654e+00, 3.50692316e-01, 1.00497838e+00, 3.06787794e+00],
       [7.90607320e-01, 3.09527984e+00, 2.42114524e+00, 2.04947916e+00],
       [3.24382176e-03, 2.82234526e+00, 3.79200212e+00, 3.46652576e+00],
       [1.33838524e-01, 6.33470826e-01, 4.25387286e+00, 4.02985249e+00]])

In [56]:
np.reshape(arr_2d, newshape=(5, 4))

array([[3.12494865e+00, 2.52019245e+00, 1.66512359e+00, 4.41634994e+00],
       [2.92805654e+00, 3.50692316e-01, 1.00497838e+00, 3.06787794e+00],
       [7.90607320e-01, 3.09527984e+00, 2.42114524e+00, 2.04947916e+00],
       [3.24382176e-03, 2.82234526e+00, 3.79200212e+00, 3.46652576e+00],
       [1.33838524e-01, 6.33470826e-01, 4.25387286e+00, 4.02985249e+00]])

In [57]:
# We can flatten an array using attribute flatten

arr_2d.flatten()


array([3.12494865e+00, 2.52019245e+00, 1.66512359e+00, 4.41634994e+00,
       2.92805654e+00, 3.50692316e-01, 1.00497838e+00, 3.06787794e+00,
       7.90607320e-01, 3.09527984e+00, 2.42114524e+00, 2.04947916e+00,
       3.24382176e-03, 2.82234526e+00, 3.79200212e+00, 3.46652576e+00,
       1.33838524e-01, 6.33470826e-01, 4.25387286e+00, 4.02985249e+00])

<div class="alert alert-block alert-info">
<b>Tip:</b> Reshape doesn't act in place while resize returns <code>None</code> and acts in place.</div>


In [58]:
print("Original shape: ", arr_2d.shape)

arr_2d.reshape(5, 4)

print("Shape after using reshape: ", arr_2d.shape)

a = arr_2d.resize(5, 4)

print("Shape after using resize: ", arr_2d.shape)


Original shape:  (4, 5)
Shape after using reshape:  (4, 5)
Shape after using resize:  (5, 4)


<span style='color:red; font-weight:bold;'>Note:</span> <code>np.resize()</code> acts like <code>np.reshape()</code>.

In [59]:
print("Original shape: ", arr_2d.shape)

np.reshape(arr_2d, (5, 4))

print("Shape after using reshape: ", arr_2d.shape)

np.resize(arr_2d, (5, 4))

print("Shape after using resize: ", arr_2d.shape)

Original shape:  (5, 4)
Shape after using reshape:  (5, 4)
Shape after using resize:  (5, 4)


<a name='joining'></a>
### 4.2 Joining arrays 


In [60]:
arr1 = np.array([[1, 2, 0, 1]])

arr2 = 6 * np.random.random((4, 4))

In [61]:
# Check the shape
print('arr1: ', arr1.shape)
print('arr2: ', arr2.shape)

arr1:  (1, 4)
arr2:  (4, 4)


In [62]:
# Joining arrays by row

np.concatenate((arr2, arr1), axis=0)

array([[4.39519938, 1.14490425, 1.59430489, 2.32748641],
       [1.59774472, 4.67115618, 2.78828997, 5.98815225],
       [5.50006861, 1.87447721, 3.72428163, 1.99962704],
       [4.09223037, 3.72611926, 2.16547115, 5.50849331],
       [1.        , 2.        , 0.        , 1.        ]])

For using `axis = 0`, we should have the same number of columns and for `axis = 1`, we should have the same number of rows.

In [63]:
# Joining arrays by column
# .T takes the transpose as well as np.transpose()
np.concatenate((arr2, arr1.T), axis=1)

array([[4.39519938, 1.14490425, 1.59430489, 2.32748641, 1.        ],
       [1.59774472, 4.67115618, 2.78828997, 5.98815225, 2.        ],
       [5.50006861, 1.87447721, 3.72428163, 1.99962704, 0.        ],
       [4.09223037, 3.72611926, 2.16547115, 5.50849331, 1.        ]])

In [64]:
# Joining by vstack which acts as using axis = 0

np.vstack((arr2, arr1))

array([[4.39519938, 1.14490425, 1.59430489, 2.32748641],
       [1.59774472, 4.67115618, 2.78828997, 5.98815225],
       [5.50006861, 1.87447721, 3.72428163, 1.99962704],
       [4.09223037, 3.72611926, 2.16547115, 5.50849331],
       [1.        , 2.        , 0.        , 1.        ]])

In [65]:
# Joining by hstack which acts as using axis = 1

np.hstack((arr2, arr1.T))

array([[4.39519938, 1.14490425, 1.59430489, 2.32748641, 1.        ],
       [1.59774472, 4.67115618, 2.78828997, 5.98815225, 2.        ],
       [5.50006861, 1.87447721, 3.72428163, 1.99962704, 0.        ],
       [4.09223037, 3.72611926, 2.16547115, 5.50849331, 1.        ]])

In [66]:
# Joining by column_stack / row_stack which acts as using axis = 1 / 0. 

np.column_stack((arr2, arr1.T))

array([[4.39519938, 1.14490425, 1.59430489, 2.32748641, 1.        ],
       [1.59774472, 4.67115618, 2.78828997, 5.98815225, 2.        ],
       [5.50006861, 1.87447721, 3.72428163, 1.99962704, 0.        ],
       [4.09223037, 3.72611926, 2.16547115, 5.50849331, 1.        ]])

<a name='splitting'></a>
### 4.3 Splitting of arrays 


The opposite of concatenation is splitting.
 
`np.split`, `np.hsplit`, `np.vsplit`

In [67]:
arr2

array([[4.39519938, 1.14490425, 1.59430489, 2.32748641],
       [1.59774472, 4.67115618, 2.78828997, 5.98815225],
       [5.50006861, 1.87447721, 3.72428163, 1.99962704],
       [4.09223037, 3.72611926, 2.16547115, 5.50849331]])

In [68]:
# Splitting with axis = 0

np.split(arr2, 2)

[array([[4.39519938, 1.14490425, 1.59430489, 2.32748641],
        [1.59774472, 4.67115618, 2.78828997, 5.98815225]]),
 array([[5.50006861, 1.87447721, 3.72428163, 1.99962704],
        [4.09223037, 3.72611926, 2.16547115, 5.50849331]])]

In [69]:
# Splitting with axis = 1

np.array_split(arr2, 2, axis=1)

[array([[4.39519938, 1.14490425],
        [1.59774472, 4.67115618],
        [5.50006861, 1.87447721],
        [4.09223037, 3.72611926]]),
 array([[1.59430489, 2.32748641],
        [2.78828997, 5.98815225],
        [3.72428163, 1.99962704],
        [2.16547115, 5.50849331]])]

In [70]:
# Using hsplit / vsplit

np.hsplit(arr2, 2)

[array([[4.39519938, 1.14490425],
        [1.59774472, 4.67115618],
        [5.50006861, 1.87447721],
        [4.09223037, 3.72611926]]),
 array([[1.59430489, 2.32748641],
        [2.78828997, 5.98815225],
        [3.72428163, 1.99962704],
        [2.16547115, 5.50849331]])]

<a name='computation'></a>
## 5. Computation on NumPy arrays 


Computation on NumPy arrays can be very fast if we use *vectorized* operators through *universal functions*, **ufuncs**.

In [71]:
# Creating two arrays

arr1d_1 = np.arange(7)
arr1d_2 = np.linspace(9, 12, len(arr1d_1))


arr2d_1 = np.random.random((4, 5))
arr2d_2 = 4 + 6 * np.random.random((4, 5))

In [72]:
# Addition of two arrays (equivalent of arr1d_1 + arr1d_2)

np.add(arr2d_1, arr2d_2)

array([[7.57298148, 5.05451181, 9.30686384, 5.45030493, 6.25630425],
       [9.88605326, 5.75480465, 7.57635189, 4.22292416, 7.44118237],
       [6.27490308, 7.93402006, 8.47860973, 7.21057738, 5.89683428],
       [7.29190697, 6.26982447, 4.86490874, 5.55885806, 5.31803991]])

In [73]:
# Subtraction of two arrays (equivalent of arr1d_1 - arr1d_2)

np.subtract(arr2d_1, arr2d_2)

array([[-7.41692924, -3.63845529, -7.41536096, -3.76219532, -5.53915092],
       [-9.12633911, -3.91432114, -7.46766107, -3.9437874 , -7.16843862],
       [-5.35673459, -7.29877831, -7.89010091, -6.30672002, -4.23985931],
       [-7.12914617, -5.06413038, -4.49792165, -5.0431271 , -3.63105947]])

In [74]:
# Multiplication of two arrays (equivalent of arr1d_1 * arr1d_2)

np.multiply(arr2d_1, arr2d_2)

array([[0.5848023 , 3.07743318, 7.90753411, 3.88792755, 2.11478749],
       [3.61099584, 4.44896665, 0.40878651, 0.56990735, 0.99617073],
       [2.66995079, 2.41912735, 2.40828264, 3.05442721, 4.19906187],
       [0.58679555, 3.41632062, 0.85900946, 1.36694299, 3.77423889]])

In [75]:
# Division of two arrays (equivalent of arr1d_1 + arr1d_2)

np.divide(arr2d_1, arr2d_2)

array([[0.01041049, 0.1628968 , 0.11311311, 0.1832412 , 0.06079912],
       [0.03995889, 0.19034642, 0.00722486, 0.03417982, 0.01866878],
       [0.07893716, 0.04170224, 0.03595328, 0.06686672, 0.16346306],
       [0.01128633, 0.10637894, 0.03919617, 0.04864475, 0.1885084 ]])

In [76]:
# Logarithm of an array

np.log10(arr2d_1)

array([[-1.10775998, -0.14994941, -0.02422299, -0.07362935, -0.44541798],
       [-0.42037978, -0.03609806, -1.26483714, -0.85521296, -0.86527518],
       [-0.33810761, -0.49809097, -0.53127702, -0.34493009, -0.08171405],
       [-1.08948017, -0.21979286, -0.73637921, -0.58860679, -0.07391995]])

In [77]:
# Exponent of an array

np.exp(arr2d_1)

array([[1.0811509 , 2.02998471, 2.57474743, 2.32577846, 1.43129076],
       [1.4620756 , 2.5098971 , 1.05584924, 1.14977742, 1.14610803],
       [1.58262402, 1.3738553 , 1.34212531, 1.57133988, 2.28985268],
       [1.08478347, 1.82731385, 1.20140721, 1.29416471, 2.32446573]])

In [78]:
# Sin of an array

np.sin(arr2d_1)

array([[0.07794697, 0.65033721, 0.81093686, 0.74734342, 0.35094178],
       [0.37078773, 0.79574806, 0.05431866, 0.1391157 , 0.13594958],
       [0.44312736, 0.31230732, 0.29002639, 0.4367014 , 0.73690977],
       [0.0812906 , 0.56698995, 0.18246557, 0.25501719, 0.74696817]])

In [79]:
# Comparison for greate, equivalent arr2d_1 > arr2d_2

np.greater(arr2d_1, arr2d_2)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [80]:
# Comparison for greate, equivalent arr2d_1 < arr2d_2

np.less(arr2d_1, arr2d_2)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [81]:
# FInding the absolute of an array, equivalent of np.absolute

np.abs([2, -1, 9, -1.2])

array([2. , 1. , 9. , 1.2])

<a name='aggregations'></a>
## 6. Aggregations 


Before doing any operation, it's good to have a summary statistics of the data.

<a name='summation'></a>
###  6.1 Summation 


In [82]:
# Let's create an array

arr1 = np.random.random((100, 100))


In [83]:
# Sum of values in an array

np.sum(arr1)

5003.9501297867755

In [84]:
# Comparing with Python built-in function

big_array = np.random.random(100000)

%timeit sum(big_array)
%timeit np.sum(big_array)

9.49 ms ± 1.1 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
72.6 µs ± 25.8 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


<a name='min_max'></a>
###  6.2 Minimum and maximum 


In [85]:
# Let's create an array

arr1 = np.random.random((6, 5))

In [86]:
# Finding max along columns

arr1.max(axis=0)

array([0.95454675, 0.80592209, 0.83338245, 0.77042827, 0.84348619])

In [87]:
# Finding max along rows
arr1.max(axis=1)

array([0.59064987, 0.93905949, 0.84348619, 0.66486399, 0.80592209,
       0.95454675])

In [88]:
# Finding min
arr1.min(axis=0)

array([0.16122773, 0.12339998, 0.00310598, 0.10653879, 0.00182586])

In [89]:
# We can use np.max / np.min as well.
np.max(arr1, axis=1)

array([0.59064987, 0.93905949, 0.84348619, 0.66486399, 0.80592209,
       0.95454675])

<a name='var_std'></a>
### 6.3 Variance and standard deviation 


In [90]:
# Let's create an array

arr1 = np.random.random((6, 5))

In [91]:
# calculating the standard deviation of the array

np.std(arr1)

0.34273506350237504

In [92]:
arr1.std()

0.34273506350237504

In [93]:
# Let's check if std is variance^0.5

arr1.std() == np.sqrt(arr1.var())

True

In [94]:
# std along rows

arr1.std(axis=1)

array([0.35771294, 0.24085549, 0.26653071, 0.39025074, 0.29958713,
       0.36384725])

In [95]:
# variance along columns

arr1.var(axis=0)

array([0.09855379, 0.0784968 , 0.06833994, 0.15192005, 0.09711345])

<a name='mean_median'></a>
###  6.4 Mean and median


In [96]:
# Let's create an array

arr1 = np.random.random((6, 5))

In [97]:
# Calculate the mean of the whole array

arr1.mean()

0.48865834632454436

In [98]:
# Calculate the mean along an axis

arr1.mean(axis=1)

array([0.53827744, 0.40127025, 0.59665278, 0.33421707, 0.33345773,
       0.7280748 ])

In [99]:
# Calculate the mean of the whole array

np.median(arr1)

0.45769839591723477

<span style='color:red; font-weight:bold;'>Note: </span> An <code>ndarray</code> doesn't have attribute median.

<a name='find_index'></a>
###  6.5 Find index 


In [100]:
# Let's create an array

arr1 = np.random.random((6, 5))
arr1[3, 3] = 0
arr1

array([[0.13342196, 0.51625798, 0.21430031, 0.14102139, 0.80624634],
       [0.9611696 , 0.47088499, 0.00758668, 0.37012156, 0.55707768],
       [0.15327368, 0.38915331, 0.69674686, 0.08540601, 0.89252822],
       [0.04101646, 0.62661837, 0.23546178, 0.        , 0.65122638],
       [0.47912935, 0.26925893, 0.80557815, 0.07393885, 0.42204269],
       [0.01963075, 0.95747755, 0.40774398, 0.4743706 , 0.72677359]])

In [101]:
# Find the indix of maximum value

arr1.argmax()

5

In [102]:
# Find the indix of minimum value

arr1.argmin()

18

In [103]:
# Find the indix of an specific value

np.where(arr1 == 0)

(array([3]), array([3]))

### [TOP ☝️](#top)
