<center>
<table style="border:none">
    <tr style="border:none">
    <th style="border:none">
        <a  href='https://colab.research.google.com/github/AmirMardan/ml_course/blob/main/7_fully_connected_nn/0_intro_to_pytorch.ipynb'><img src='https://colab.research.google.com/assets/colab-badge.svg'></a>
    </th>
    <th style="border:none">
        <a  href='https://github1s.com/AmirMardan/ml_course/blob/main/7_fully_connected_nn/0_intro_to_pytorch.ipynb'><img src='../imgs/open_vscode.svg' height=20px width=115px></a>
    </th>
    </tr>
</table>
</center>


This notebook is created by <a href='https://amirmardan.github.io/'> Amir Mardan</a>. For any feedback or suggestion, please contact me via <a href="mailto:mardan.amir.h@gmail.com">email</a>, (mardan.amir.h@gmail.com).



<a name='top'></a>
# PyTorch

PyTorch is another powerful open-source and end-to-end platform for building machine learning models and numerical modeling.
Being end-to-end, we can perform all required steps of machine learning using PyTorch.

This notebook will cover the following topics:

- [1. Creating a Tensor](#Tensor)
- [2 . Numerical Operations In PyTorch](#Operations)
    - [2.1 In-place Operations](#inplace)
    - [2.2 Conditional Operators](#conditional)
- [3. Slicing, Shape, and Size](#slicing)
- [4. Concatenation and Splitting](#concatenation)
- [5. Tensor Operations and Gradients](#Gradients)
    

In [1]:
import torch


<a name='Tensor'></a>
## 1 . Creating a Tensor


The fundamental data abstraction in PyTorch is `Tensor` object, which is the alternative of `ndarray` in NumPy.

In [2]:
uninitialized = torch.Tensor(3, 2)

uninitialized

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [3]:
rand_tensor = 2 + 3 * torch.rand(3, 2)
rand_tensor

tensor([[4.8156, 3.7266],
        [2.3189, 3.4254],
        [2.6958, 3.1957]])

In [4]:
ones_tensor = torch.ones(3, 2)
ones_tensor

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [5]:
zeros_tensor = torch.zeros(3, 2)
zeros_tensor

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
torch.tensor([1,2.])

tensor([1., 2.])

In [7]:
torch.IntTensor([1, 2])

tensor([1, 2], dtype=torch.int32)

Torch defines 10 tensor types with CPU and GPU variants which can be found [here](https://pytorch.org/docs/master/tensors.html)

<a name='Operations'></a>
## 2 . Numerical Operations In PyTorch


In [8]:
x = torch.ones(3, 2)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [9]:
y = 4 * torch.rand(x.shape)
y

tensor([[3.5460, 2.1881],
        [2.5328, 3.8709],
        [1.0225, 1.3291]])

In [10]:
z = 5 * torch.rand(2, 3)
z

tensor([[3.3617, 1.2843, 3.6951],
        [0.6709, 1.1147, 2.8594]])

**Summation**

In [11]:
x + y

tensor([[4.5460, 3.1881],
        [3.5328, 4.8709],
        [2.0225, 2.3291]])

In [12]:
x.add(y)

tensor([[4.5460, 3.1881],
        [3.5328, 4.8709],
        [2.0225, 2.3291]])

**Multiplication**

In [13]:
x * y

tensor([[3.5460, 2.1881],
        [2.5328, 3.8709],
        [1.0225, 1.3291]])

In [14]:
x.mul(y)

tensor([[3.5460, 2.1881],
        [2.5328, 3.8709],
        [1.0225, 1.3291]])

**Matrix multiplication**

In [15]:
(x + y) @ z

tensor([[17.4213,  9.3923, 25.9139],
        [15.1442,  9.9667, 26.9818],
        [ 8.3616,  5.1937, 14.1330]])

In [16]:
(x + y).matmul(z)

tensor([[17.4213,  9.3923, 25.9139],
        [15.1442,  9.9667, 26.9818],
        [ 8.3616,  5.1937, 14.1330]])

<a name='inplace'></a>
### 2.1 In-place Operations


By adding an underscore to some methods, we can make the operations in place. For example, `tensor1.add(tensor2)` is an out-place operation while `tensor1.add_(tensor2)` is in place.

In [17]:
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [18]:
y 

tensor([[3.5460, 2.1881],
        [2.5328, 3.8709],
        [1.0225, 1.3291]])

In [19]:
x1 = x.add(y)
x1

tensor([[4.5460, 3.1881],
        [3.5328, 4.8709],
        [2.0225, 2.3291]])

In [20]:
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [21]:
x2 = x.add_(y)
x2


tensor([[4.5460, 3.1881],
        [3.5328, 4.8709],
        [2.0225, 2.3291]])

In [22]:
x

tensor([[4.5460, 3.1881],
        [3.5328, 4.8709],
        [2.0225, 2.3291]])

<a name='conditional'></a>
### 2.2 Conditional Operators


In [23]:
x > y

tensor([[True, True],
        [True, True],
        [True, True]])

In [24]:
x < y

tensor([[False, False],
        [False, False],
        [False, False]])

In [25]:
y >= torch.rand(3, 2)

tensor([[True, True],
        [True, True],
        [True, True]])

<a name='slicing'></a>
## 3. Slicing, Shape, and Size

In [26]:
y

tensor([[3.5460, 2.1881],
        [2.5328, 3.8709],
        [1.0225, 1.3291]])

In [27]:
y[0, 0]

tensor(3.5460)

In [28]:
y[:2, 0]

tensor([3.5460, 2.5328])

In [29]:
y.shape

torch.Size([3, 2])

In [30]:
y.size()

torch.Size([3, 2])

In [31]:
# Transpose 

y.T

tensor([[3.5460, 2.5328, 1.0225],
        [2.1881, 3.8709, 1.3291]])

<a name='concatenation'></a>
## 4. Concatenation and Splitting

In [32]:
# Concatenation

torch.cat((y, x), dim=0)

tensor([[3.5460, 2.1881],
        [2.5328, 3.8709],
        [1.0225, 1.3291],
        [4.5460, 3.1881],
        [3.5328, 4.8709],
        [2.0225, 2.3291]])

In [33]:
torch.cat((y, x), dim=1)

tensor([[3.5460, 2.1881, 4.5460, 3.1881],
        [2.5328, 3.8709, 3.5328, 4.8709],
        [1.0225, 1.3291, 2.0225, 2.3291]])

By stacking, we create a new dimension.

In [34]:
stacked = torch.stack((y, x))
stacked.shape

torch.Size([2, 3, 2])

`split` splits the tensor to your desired size.

In [35]:
# Spliting

torch.split(x, 1)

(tensor([[4.5460, 3.1881]]),
 tensor([[3.5328, 4.8709]]),
 tensor([[2.0225, 2.3291]]))

`chunk` splits the tensor into as many chunks as you want.

In [36]:
torch.chunk(x, 2)

(tensor([[4.5460, 3.1881],
         [3.5328, 4.8709]]),
 tensor([[2.0225, 2.3291]]))

To remove the dimensions with the size of 1, you can use `squeeze`.

In [37]:
x_unsqueeze = torch.rand(3, 4, 1)
x_unsqueeze.shape

torch.Size([3, 4, 1])

In [38]:
x_unsqueeze.squeeze().shape

torch.Size([3, 4])

You can return that dimension using `unsqueeze`.

In [39]:
x_unsqueeze.squeeze().unsqueeze(dim=2).shape

torch.Size([3, 4, 1])

In [40]:
x_unsqueeze = torch.rand(3, 1, 4)
x_unsqueeze.shape

torch.Size([3, 1, 4])

In [41]:
x_unsqueeze.squeeze().shape

torch.Size([3, 4])

We can convert a PyTroch tensor to NumPy array.

In [42]:
x.numpy()

array([[4.5460067, 3.1881428],
       [3.5328345, 4.8708553],
       [2.0224898, 2.3290946]], dtype=float32)

<a name='Gradients'></a>
## 5. Tensor Operations and Gradients

We can calculate the gradient of a function with respect to its variable easily by first specifying the gradient of which variable is required,

```Python
requires_grad=True
``` 
and then call the backward attribute on the output of the function.

In [43]:
x = torch.tensor(2.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(10., requires_grad=True)

x.dtype


torch.float32

In [44]:
y = w * x + b

In [45]:
# compute the gradient

y.backward()

Now, the gradient of the output with respect to all parameters is available.


<span style='color:red; font-weight:bold;'>Note: </span> We haven't specified that `x` requires gradient, so the $\frac{\partial y}{\partial x}$ is None.

In [46]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(2.)
dy/db: tensor(1.)


### [TOP ☝️](#top)
